title: kadiri world
author: KADIRI ABDULKADIR AIYEGBENI
email: kadiriaiyegbenia@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  an  educative filled with smorgasbord tech stories 
theme: minima 

# social links
twitter_username: https://twitter.com/kadiri a**a # DO NOT include the @ character, or else the build will fail!
github_username:  https://github.com/controangel # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
